import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

// Artifact generation functions
async function generatePhaseArtifacts(supabaseClient: any, runId: string, phase: string, brief: any) {
  console.log(`🎨 Generating artifacts for ${phase} phase of run ${runId}`)
  
  try {
    switch (phase) {
      case 'intake':
        await generateIntakeArtifacts(supabaseClient, runId, brief);
        break;
      case 'market':
        await generateMarketArtifacts(supabaseClient, runId, brief);
        break;
      case 'synthesis':
        await generateSynthesisArtifacts(supabaseClient, runId, brief);
        break;
      case 'deconstruct':
        await generateDeconstructArtifacts(supabaseClient, runId, brief);
        break;
      case 'prioritize':
        await generatePrioritizeArtifacts(supabaseClient, runId, brief);
        break;
      case 'build':
        await generateBuildArtifacts(supabaseClient, runId, brief);
        break;
      case 'qa':
        await generateQAArtifacts(supabaseClient, runId, brief);
        break;
      case 'deploy':
        await generateDeployArtifacts(supabaseClient, runId, brief);
        break;
      case 'measure':
        await generateMeasureArtifacts(supabaseClient, runId, brief);
        break;
      case 'decision':
        await generateDecisionArtifacts(supabaseClient, runId, brief);
        break;
    }
  } catch (error) {
    console.error(`❌ Failed to generate artifacts for ${phase}:`, error);
  }
}

async function generateMarketArtifacts(supabaseClient: any, runId: string, brief: any) {
  const marketData = {
    trends: ['hypercasual', 'merge', 'idle', 'puzzle', 'arcade'],
    topGames: ['Subway Surfers', 'Candy Crush Saga', 'Among Us', 'Wordle', 'Clash Royale'],
    insights: `Market analysis for ${brief.industry} games targeting ${brief.targetAudience || 'general audience'}. Strong preference for ${brief.theme}-themed games with quick-session gameplay.`,
    competitorAnalysis: {
      directCompetitors: 3,
      marketGap: `Opportunity in ${brief.theme} + ${brief.industry} combination`,
      recommendedFeatures: ['Progressive difficulty', 'Social sharing', 'Achievement system']
    },
    marketSize: Math.floor(Math.random() * 50 + 10) + 'M downloads/month',
    confidence: 0.85
  };

  await supabaseClient
    .from('orchestrator_artifacts')
    .insert({
      run_id: runId,
      phase: 'market',
      kind: 'market_scan',
      path: `runs/${runId}/market_scan.json`,
      meta: {
        filename: 'market_scan.json',
        size: JSON.stringify(marketData).length,
        contentType: 'application/json',
        data: marketData
      }
    });
}

async function generateSynthesisArtifacts(supabaseClient: any, runId: string, brief: any) {
  const synthesisContent = `# Theme Analysis: ${brief.theme}

## Key Insights

- **Visual Style**: Modern, ${brief.industry === 'education' ? 'educational' : 'engaging'} design
- **Core Mechanics**: ${brief.theme.includes('space') ? 'Physics-based movement' : 'Simple tap/swipe interactions'}
- **Target Audience**: ${brief.targetAudience || 'General audience'}
- **Unique Value Proposition**: Combines ${brief.theme} theming with ${brief.goal}

## Market Positioning

The ${brief.theme} theme in ${brief.industry} games shows strong potential for:
1. Immediate visual appeal
2. Clear gameplay metaphors
3. Expandable content universe

## Recommendations

1. Focus on immediate feedback loops
2. Implement progressive difficulty scaling
3. Add social sharing features for viral growth
4. Consider seasonal content updates

---

*Generated by SynthesisAgent v2.1*`;

  await supabaseClient
    .from('orchestrator_artifacts')
    .insert({
      run_id: runId,
      phase: 'synthesis',
      kind: 'theme_analysis',
      path: `runs/${runId}/theme_analysis.md`,
      meta: {
        filename: 'theme_analysis.md',
        size: synthesisContent.length,
        contentType: 'text/markdown',
        data: synthesisContent
      }
    });
}

async function generateBuildArtifacts(supabaseClient: any, runId: string, brief: any) {
  const buildBrief = `# Build Brief: ${brief.theme}

## Technical Requirements

- **Engine**: Phaser 3.70+
- **Resolution**: 720x1280 (mobile portrait)
- **File Size**: <2MB total
- **Performance**: 60fps target, 30fps minimum

## Game Design Document

### Core Loop
1. Player ${brief.theme.includes('space') ? 'pilots spacecraft' : 'navigates challenges'}
2. ${brief.goal.includes('teach') ? 'Educational content integrated into gameplay' : 'Score-based progression system'}
3. Progressive difficulty with ${brief.theme} theming
4. Achievement unlocks and social sharing

### Art Direction
- **Color Palette**: ${brief.theme.includes('space') ? 'Deep blues, cosmic purples, bright stars' : 'Vibrant, accessible colors'}
- **Style**: ${brief.industry === 'education' ? 'Friendly, approachable cartoon style' : 'Modern, sleek design'}
- **UI/UX**: Intuitive touch controls, clear visual hierarchy

### Success Metrics
- Session length: 60-180 seconds
- Replay rate: >40%
- ${brief.industry === 'education' ? 'Learning objective completion: >80%' : 'Share rate: >5%'}

## Implementation Plan

### Phase 1: Core Mechanics (Week 1)
- Basic ${brief.theme} environment
- Core interaction system
- Score/progress tracking

### Phase 2: Content & Polish (Week 2)
- Level progression system
- Visual effects and juice
- Audio integration
- Performance optimization

---

*Generated by BuildAgent v3.2*`;

  await supabaseClient
    .from('orchestrator_artifacts')
    .insert({
      run_id: runId,
      phase: 'build',
      kind: 'build_brief',
      path: `runs/${runId}/build_brief.md`,
      meta: {
        filename: 'build_brief.md',
        size: buildBrief.length,
        contentType: 'text/markdown',
        data: buildBrief
      }
    });
}

// Placeholder functions for other phases
async function generateIntakeArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`📋 Intake artifacts for ${brief.theme} - brief processed`);
}

async function generateDeconstructArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`🔍 Deconstruct artifacts for ${brief.theme} - analyzing successful games`);
}

async function generatePrioritizeArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`🎯 Prioritize artifacts for ${brief.theme} - ranking opportunities`);
}

async function generateQAArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`🧪 QA artifacts for ${brief.theme} - testing reports generated`);
}

async function generateDeployArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`🚀 Deploy artifacts for ${brief.theme} - deployment package ready`);
}

async function generateMeasureArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`📊 Measure artifacts for ${brief.theme} - analytics dashboard`);
}

async function generateDecisionArtifacts(supabaseClient: any, runId: string, brief: any) {
  console.log(`🎯 Decision artifacts for ${brief.theme} - recommendations generated`);
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const url = new URL(req.url)
    // The path comes as /orchestrator-api/... so we need to remove that prefix
    const path = url.pathname.replace('/orchestrator-api', '') || '/'
    const method = req.method

    // Log requests for monitoring
    console.log(`${method} ${path}`)

    // Routes
    if (method === 'GET' && path === '/runs') {
      // List all runs
      const { data: runs, error } = await supabaseClient
        .from('orchestrator_runs')
        .select(`
          *,
          blockers:orchestrator_manual_tasks!inner(*)
        `)
        .eq('blockers.status', 'open')
        .order('created_at', { ascending: false })

      if (error) {
        throw error
      }

      return new Response(
        JSON.stringify(runs),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      )
    }

    if (method === 'POST' && path === '/runs') {
      // Create new run
      const body = await req.json()
      
      const { data: run, error } = await supabaseClient
        .from('orchestrator_runs')
        .insert({
          brief: body.brief,
          status: 'queued',
          phase: 'intake'
        })
        .select()
        .single()

      if (error) {
        throw error
      }

      return new Response(
        JSON.stringify(run),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 201 
        }
      )
    }

    if (method === 'POST' && path.match(/^\/runs\/[^\/]+\/advance$/)) {
      // Advance run to next phase
      const runId = path.split('/')[2]
      
      // Get current run
      const { data: currentRun, error: fetchError } = await supabaseClient
        .from('orchestrator_runs')
        .select('*')
        .eq('id', runId)
        .single()

      if (fetchError) {
        throw fetchError
      }

      // Determine next phase and status
      const phaseOrder = ['intake', 'market', 'synthesis', 'deconstruct', 'prioritize', 'build', 'qa', 'deploy', 'measure', 'decision']
      const currentPhaseIndex = phaseOrder.indexOf(currentRun.phase)
      
      let nextPhase = currentRun.phase
      let nextStatus = 'running'
      
      if (currentRun.status === 'queued') {
        nextStatus = 'running'
      } else if (currentRun.status === 'running' || currentRun.status === 'awaiting_human') {
        // Advance to next phase
        if (currentPhaseIndex < phaseOrder.length - 1) {
          nextPhase = phaseOrder[currentPhaseIndex + 1]
          nextStatus = 'running'
        } else {
          nextStatus = 'done'
        }
      }

      // Simulate LLM processing with realistic delays and potential human intervention
      const shouldRequireHuman = Math.random() < 0.3 // 30% chance of requiring human intervention
      if (nextStatus === 'running' && shouldRequireHuman && ['synthesis', 'prioritize', 'qa'].includes(nextPhase)) {
        nextStatus = 'awaiting_human'
        
        // Create a manual task
        await supabaseClient
          .from('orchestrator_manual_tasks')
          .insert({
            run_id: runId,
            phase: nextPhase,
            task_type: 'review',
            status: 'pending',
            title: `Review ${nextPhase} phase results`,
            description: `Please review the ${nextPhase} phase output and approve to continue.`,
            assignee: 'operator'
          })
      }

      const { data: run, error } = await supabaseClient
        .from('orchestrator_runs')
        .update({
          status: nextStatus,
          phase: nextPhase,
          updated_at: new Date().toISOString()
        })
        .eq('id', runId)
        .select()
        .single()

      if (error) {
        throw error
      }

      // Generate artifacts for the completed phase
      await generatePhaseArtifacts(supabaseClient, runId, currentRun.phase, currentRun.brief);
      
      // Log the advancement
      console.log(`🚀 Run ${runId} advanced from ${currentRun.phase}:${currentRun.status} to ${nextPhase}:${nextStatus}`)

      return new Response(
        JSON.stringify({ success: true, run }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      )
    }

    if (method === 'POST' && path.match(/^\/tasks\/[^\/]+\/complete$/)) {
      // Complete manual task
      const taskId = path.split('/')[2]
      
      const { data: task, error } = await supabaseClient
        .from('orchestrator_manual_tasks')
        .update({
          status: 'completed',
          completed_at: new Date().toISOString()
        })
        .eq('id', taskId)
        .select()
        .single()

      if (error) {
        throw error
      }

      return new Response(
        JSON.stringify({ success: true, task }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      )
    }

    if (method === 'POST' && path === '/process-runs') {
      // Auto-process running runs (simulate LLM work)
      const { data: runningRuns, error: fetchError } = await supabaseClient
        .from('orchestrator_runs')
        .select('*')
        .eq('status', 'running')

      if (fetchError) {
        throw fetchError
      }

      const processedRuns = []
      
      for (const run of runningRuns) {
        // Simulate processing time (runs that have been running for more than 30 seconds)
        const runningTime = Date.now() - new Date(run.updated_at).getTime()
        
        if (runningTime > 30000) { // 30 seconds
          const phaseOrder = ['intake', 'market', 'synthesis', 'deconstruct', 'prioritize', 'build', 'qa', 'deploy', 'measure', 'decision']
          const currentPhaseIndex = phaseOrder.indexOf(run.phase)
          
          let nextPhase = run.phase
          let nextStatus = 'running'
          
          // Advance to next phase
          if (currentPhaseIndex < phaseOrder.length - 1) {
            nextPhase = phaseOrder[currentPhaseIndex + 1]
            
            // 30% chance of requiring human intervention in key phases
            const shouldRequireHuman = Math.random() < 0.3
            if (shouldRequireHuman && ['synthesis', 'prioritize', 'qa'].includes(nextPhase)) {
              nextStatus = 'awaiting_human'
              
              // Create a manual task
              await supabaseClient
                .from('orchestrator_manual_tasks')
                .insert({
                  run_id: run.id,
                  phase: nextPhase,
                  task_type: 'review',
                  status: 'pending',
                  title: `Review ${nextPhase} phase results`,
                  description: `Please review the ${nextPhase} phase output and approve to continue.`,
                  assignee: 'operator'
                })
            }
          } else {
            nextStatus = 'done'
          }

          // Update the run
          const { data: updatedRun, error: updateError } = await supabaseClient
            .from('orchestrator_runs')
            .update({
              status: nextStatus,
              phase: nextPhase,
              updated_at: new Date().toISOString()
            })
            .eq('id', run.id)
            .select()
            .single()

          if (!updateError) {
            processedRuns.push(updatedRun)
            console.log(`🤖 Auto-advanced run ${run.id} from ${run.phase} to ${nextPhase} (${nextStatus})`)
          }
        }
      }

      return new Response(
        JSON.stringify({ processed: processedRuns.length, runs: processedRuns }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      )
    }

    if (method === 'GET' && path === '/health') {
      return new Response(
        JSON.stringify({ 
          status: 'healthy', 
          timestamp: new Date().toISOString(),
          path: '/orchestrator-api/health'
        }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      )
    }

    // Route not found
    console.log('❌ Route not found:', method, path)
    return new Response(
      JSON.stringify({ error: 'Route not found' }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 404 
      }
    )

  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    )
  }
})
